name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/thrdchld/ghostwriter-komitan hf-space

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ hf-space/

          cd hf-space

          git add .

          git diff --cached --quiet || git commit -m "Auto deploy from GitHub"

          git push